package app.zhinong.ai;

import app.zhinong.business.Store;
import app.zhinong.database.DatabaseTime;
import app.zhinong.security.Identity;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/** All figures are computed from tenant-scoped records, never generated by the model. */
@Service
public class AgronomyAnalysis {
  private final Store store;
  private final JdbcTemplate db;
  public AgronomyAnalysis(Store store, JdbcTemplate db) { this.store=store; this.db=db; }

  public Map<String,Object> report(String farmId) {
    var farm=store.get("farms",farmId);
    String tenant=Identity.tenant();
    var now=OffsetDateTime.now();
    var since=LocalDate.now().minusDays(6).atStartOfDay(ZoneId.systemDefault()).toOffsetDateTime();
    var crops=db.queryForList("""
      SELECT p.id AS "plotId",p.name AS "plotName",s.crop,s.variety,s.start_date AS "startDate",s.end_date AS "endDate",s.area_mu AS "areaMu"
      FROM plantings s JOIN plots p ON p.tenant_id=s.tenant_id AND p.id=s.plot_id
      WHERE p.tenant_id=? AND p.farm_id=? AND s.status='ACTIVE' AND s.start_date<=? AND s.end_date>=?
      ORDER BY p.name,s.start_date
      """,tenant,farmId,LocalDate.now(),LocalDate.now());
    crops.forEach(c -> c.put("daysAfterPlanting",java.time.temporal.ChronoUnit.DAYS.between(LocalDate.parse(c.get("startDate").toString()),LocalDate.now())));
    var sensors=db.queryForList("""
      SELECT d.id AS "deviceId",d.name AS "deviceName",a.plot_id AS "plotId",p.name AS "plotName",
        t.metric,t.measured_value AS "value",t.measured_at AS "time",t.source
      FROM devices d JOIN asset_profiles a ON a.tenant_id=d.tenant_id AND a.device_id=d.id
      JOIN telemetry_readings t ON t.tenant_id=d.tenant_id AND t.device_id=d.id
      LEFT JOIN plots p ON p.tenant_id=a.tenant_id AND p.id=a.plot_id
      WHERE d.tenant_id=? AND d.farm_id=? AND a.lifecycle='ACTIVE'
        AND t.metric IN ('SOIL_MOISTURE','TEMPERATURE','HUMIDITY','WIND_SPEED','RAINFALL','PEST_COUNT')
        AND NOT EXISTS(SELECT 1 FROM telemetry_readings n WHERE n.tenant_id=t.tenant_id AND n.device_id=t.device_id
          AND n.metric=t.metric AND (n.measured_at>t.measured_at OR (n.measured_at=t.measured_at AND n.id>t.id)))
      ORDER BY d.name,t.metric
      """,tenant,farmId);
    sensors.forEach(s -> { var time=DatabaseTime.offset(s.get("time"));
      s.put("fresh",time!=null && time.toInstant().isAfter(now.toInstant().minusSeconds(900)) && !time.toInstant().isAfter(now.toInstant().plusSeconds(60))); });
    var bucket=store.sql().calendarDate("t.measured_at");
    var weather=db.queryForList("SELECT "+bucket+" AS \"date\",t.metric,ROUND(AVG(t.measured_value),2) AS \"average\","
      +"MIN(t.measured_value) AS \"min\",MAX(t.measured_value) AS \"max\",COUNT(*) AS \"samples\" "
      +"FROM telemetry_readings t JOIN devices d ON d.tenant_id=t.tenant_id AND d.id=t.device_id "
      +"JOIN asset_profiles a ON a.tenant_id=d.tenant_id AND a.device_id=d.id "
      +"WHERE d.tenant_id=? AND d.farm_id=? AND a.device_type='WEATHER' AND t.measured_at>=? AND t.measured_at<=? "
      +"AND t.metric IN ('TEMPERATURE','HUMIDITY','WIND_SPEED','RAINFALL') GROUP BY "+bucket+",t.metric ORDER BY "+bucket+",t.metric",
      tenant,farmId,since,now);
    var issues=db.queryForList("""
      SELECT i.category,i.severity,i.description,i.status,p.name AS "plotName"
      FROM field_issues i JOIN plots p ON p.tenant_id=i.tenant_id AND p.id=i.plot_id
      WHERE i.tenant_id=? AND p.farm_id=? AND i.status<>'RESOLVED' ORDER BY i.created_at DESC LIMIT 30
      """,tenant,farmId);
    var totals=db.queryForMap("""
      SELECT COUNT(*) AS "records",COALESCE(SUM(r.yield_kg),0) AS "yieldKg",MIN(r.record_date) AS "firstDate",MAX(r.record_date) AS "lastDate"
      FROM production r JOIN plots p ON p.tenant_id=r.tenant_id AND p.id=r.plot_id WHERE r.tenant_id=? AND p.farm_id=?
      """,tenant,farmId);
    var tasks=db.queryForMap("""
      SELECT COUNT(*) AS "pending",COALESCE(SUM(CASE WHEN t.due_date<? THEN 1 ELSE 0 END),0) AS "overdue"
      FROM farm_tasks t JOIN plots p ON p.tenant_id=t.tenant_id AND p.id=t.plot_id
      WHERE t.tenant_id=? AND p.farm_id=? AND t.status IN ('PENDING','RUNNING')
      """,LocalDate.now(),tenant,farmId);
    var pestHistory=db.queryForList(("""
      SELECT %s AS "date",ROUND(AVG(t.measured_value),2) AS "averageCount",MAX(t.measured_value) AS "peakCount",COUNT(*) AS "samples"
      FROM telemetry_readings t JOIN devices d ON d.tenant_id=t.tenant_id AND d.id=t.device_id
      WHERE t.tenant_id=? AND d.farm_id=? AND t.metric='PEST_COUNT' AND t.measured_at>=? AND t.measured_at<=?
      GROUP BY %s ORDER BY %s
      """).formatted(bucket,bucket,bucket),tenant,farmId,since,now);
    var cautions=new ArrayList<String>();
    for(var s:sensors) {
      if(!Boolean.TRUE.equals(s.get("fresh"))) continue;
      double value=((Number)s.get("value")).doubleValue();String metric=s.get("METRIC").toString();
      if(metric.equals("TEMPERATURE") && value>=35) cautions.add(s.get("deviceName")+" 温度 "+value+"℃：检查遮阴、通风和根层水分，避免高温时段集中作业。");
      if(metric.equals("WIND_SPEED") && value>=10) cautions.add(s.get("deviceName")+" 风速 "+value+"m/s：核对设施和田间作业条件，谨慎安排喷施。");
      if(metric.equals("HUMIDITY") && value>=90) cautions.add(s.get("deviceName")+" 湿度 "+value+"%：检查通风和叶面结露，结合巡田判断病害风险。");
    }
    var moistureStats=sensors.stream().filter(s -> "SOIL_MOISTURE".equals(s.get("METRIC")) && Boolean.TRUE.equals(s.get("fresh")))
      .mapToDouble(s -> ((Number)s.get("value")).doubleValue()).summaryStatistics();
    String moistureRange=moistureStats.getCount()==0?"":String.format(Locale.ROOT,"读数范围 %.1f–%.1f%%。",moistureStats.getMin(),moistureStats.getMax());
    long moisture=sensors.stream().filter(s -> "SOIL_MOISTURE".equals(s.get("METRIC")) && Boolean.TRUE.equals(s.get("fresh"))).count();
    long pests=sensors.stream().filter(s -> "PEST_COUNT".equals(s.get("METRIC")) && Boolean.TRUE.equals(s.get("fresh"))).count();
    long fresh=sensors.stream().filter(s -> Boolean.TRUE.equals(s.get("fresh"))).count();
    var cards=List.of(
      card("growth","苗情",crops.isEmpty()?"资料不足":"种植档案",crops.isEmpty()?"没有处于有效日期内的在种计划，请先核对种植档案。":"有 "+crops.size()+" 项在种计划。生育阶段只能由播种日期粗估；缺少株高、叶色和图像测量，请结合巡田确认。"),
      card("moisture","墒情",moisture==0?"资料不足":"监测可用","有 "+moisture+" 个新鲜土壤水分测点。"+moistureRange+"应按作物、土壤和根层校准阈值；水稻不能直接套用旱作灌溉阈值。"),
      card("pest","虫情",pests==0?"资料不足":"监测可用","有 "+pests+" 个新鲜虫情测点。计数不等于虫种鉴定或发生率；结合诱捕器检查与田间取样，不据此自动施药。"),
      card("disaster","灾情",issues.isEmpty()&&cautions.isEmpty()?"待巡查核实":"有风险线索","当前有 "+issues.size()+" 项未关闭现场问题（最多展示30项），"+cautions.size()+" 条监测风险提示。高温、大风及积水需人工核实；没有问题记录不等于无灾害。")
    );
    var out=new LinkedHashMap<String,Object>();
    out.put("farmId",farmId); out.put("farmName",farm.get("NAME"));out.put("generatedAt",now);
    out.put("dataPolicy","SYNTHETIC_RESEARCH");out.put("windowDays",7);out.put("freshMeasurements",fresh);
    out.put("conditions",cards);out.put("crops",crops);out.put("sensors",sensors);out.put("weather",weather);
    out.put("issues",issues);out.put("production",totals);
    out.put("tasks",tasks);out.put("pestHistory",pestHistory);out.put("cautions",cautions);
    out.put("thresholdNotice","35℃高温、10m/s大风、90%高湿为教学筛查阈值，不是特定作物灾害标准；需结合品种、持续时间及现场检查。");
    out.put("weatherNotice","近7天站点观测趋势，不是未来天气预报。当日均值仅覆盖已采集时段，不宜与完整日均值直接比较。累计雨量仅展示读数范围，不按采样点相加；尚未接入预报服务。");
    out.put("sources",List.of("有效种植计划","近7天气象站读数","各测点最新读数（15分钟内视为新鲜）","未关闭现场问题","历史生产记录"));
    return out;
  }
  private Map<String,String> card(String code,String name,String state,String advice) {
    return Map.of("code",code,"name",name,"state",state,"advice",advice);
  }
}
