export const labels = {
  ADMIN: "农场主 / 租户管理员",
  OPERATOR: "操作员",
  VIEWER: "查看者",
  PLATFORM_ADMIN: "平台管理员",
  PLANNED: "待开始",
  ACTIVE: "进行中",
  FINISHED: "已结束",
  PENDING: "待执行",
  RUNNING: "执行中",
  COMPLETED: "已完成",
  CANCELLED: "已取消",
  SOWING: "播种",
  IRRIGATION: "灌溉",
  FERTILIZING: "施肥",
  HARVEST: "收获",
  INSPECTION: "巡查",
  PROTECTION: "植保防治",
  MANUAL: "人工录入",
  SIMULATED: "模拟采集",
  TEMPERATURE: "温度",
  HUMIDITY: "空气湿度",
  SOIL_MOISTURE: "土壤水分",
};
export const menus = [
  {
    id: "daily",
    title: "今日农场",
    icon: "today",
    group: "日常作业",
    description: "查看我的待办、上报现场问题，跟进每一次作业",
  },
  {
    id: "simulation",
    title: "经营模拟",
    icon: "simulation",
    group: "分析与管理",
    description: "使用公开天气和农场快照，对比季度或年度经营方案",
  },
  {
    id: "dashboard",
    title: "农场概览",
    icon: "overview",
    group: "农场与设备",
    description: "选择农场，查看平面图、设备与交互式经营数据",
  },
  {
    id: "operations",
    title: "运行概览",
    icon: "operations",
    group: "农场与设备",
    description: "一屏查看设备上报是否正常、土壤水分走势和各项作业进展",
  },
  {
    id: "farms",
    noun: "农场",
    title: "农场档案",
    icon: "farms",
    group: "农场与设备",
    description: "管理农场资料，进入独立的地图与生产工作台",
    columns: [
      ["name", "农场名称"],
      ["description", "经营说明"],
    ],
  },
  {
    id: "plots",
    noun: "地块",
    empty: "还没有地块。先建好地块，种植计划、农事任务和设备才能落到具体的田上。",
    title: "地块管理",
    icon: "plots",
    group: "农场与设备",
    description: "按农场管理地块、面积与作物",
    columns: [
      ["name", "地块名称"],
      ["farmName", "所属农场"],
      ["areaMu", "面积 / 亩"],
      ["crop", "当前作物"],
    ],
  },
  {
    id: "plantings",
    noun: "种植计划",
    empty: "还没有种植计划。为地块安排作物和起止日期后，农场概览会显示当季种植。",
    title: "种植计划",
    icon: "plantings",
    group: "农场与设备",
    description: "安排地块种植周期，追踪作物生长阶段",
    columns: [
      ["farmName", "所属农场"],
      ["plotName", "地块"],
      ["crop", "作物"],
      ["variety", "品种"],
      ["areaMu", "面积 / 亩"],
      ["startDate", "开始日期"],
      ["endDate", "结束日期"],
      ["status", "状态"],
    ],
  },
  {
    id: "tasks",
    noun: "农事任务",
    empty: "还没有农事任务。在今日农场安排农事，或从现场问题直接派工。",
    title: "农事任务",
    icon: "tasks",
    group: "日常作业",
    description: "从任务安排到执行完成，留存农事过程",
    columns: [
      ["title", "任务名称"],
      ["farmName", "所属农场"],
      ["plotName", "地块"],
      ["taskType", "类型"],
      ["dueDate", "计划日期"],
      ["status", "状态"],
      ["note", "备注"],
    ],
  },
  {
    id: "production",
    noun: "生产记录",
    empty: "还没有生产记录。每次收获后登记产量，农场概览会自动汇总产量。",
    title: "生产记录",
    icon: "production",
    group: "日常作业",
    description: "登记各地块的收获产量",
    columns: [
      ["farmName", "所属农场"],
      ["plotName", "地块"],
      ["recordDate", "记录日期"],
      ["yieldKg", "产量 / kg"],
      ["note", "备注"],
    ],
  },
  {
    id: "devices",
    noun: "监测点",
    title: "设备台账",
    icon: "devices",
    group: "农场与设备",
    description: "管理设备点位、多指标监测、接入配置与告警",
    columns: [
      ["name", "监测点"],
      ["farmName", "农场"],
      ["metric", "指标"],
      ["unit", "单位"],
      ["adapter", "数据方式"],
    ],
  },
  {
    id: "members",
    noun: "成员",
    empty: "还没有其他成员。添加操作员和查看者，分工处理农事。",
    title: "成员权限",
    icon: "members",
    group: "分析与管理",
    description: "管理本租户成员与角色",
    admin: true,
    columns: [
      ["username", "账号"],
      ["displayName", "姓名"],
      ["role", "角色"],
      ["enabled", "启用状态"],
    ],
  },
  {
    id: "audit",
    noun: "操作记录",
    empty: "还没有操作记录。新增、修改或删除业务数据后会记录在这里。",
    title: "操作日志",
    icon: "audit",
    group: "分析与管理",
    description: "查看本租户的业务变更记录",
    columns: [
      ["actor", "操作账号"],
      ["action", "操作"],
      ["resourceId", "记录标识"],
      ["occurredAt", "时间"],
    ],
  },
  {
    id: "platform/tenants",
    noun: "租户",
    empty: "还没有租户。新增租户后，租户管理员即可登录建立农场。",
    title: "租户管理",
    icon: "tenants",
    group: "平台管理",
    description: "创建独立租户，管理服务启用状态",
    platform: true,
    columns: [
      ["code", "租户代码"],
      ["name", "租户名称"],
      ["enabled", "启用状态"],
    ],
  },
];

const text = (key, label, max = 100) => ({ key, label, type: "text", max });
const choice = (key, label, options) => ({
  key,
  label,
  type: "select",
  options,
});
const relation = (key, label, source) => ({
  key,
  label,
  type: "select",
  source,
});
const number = (key, label) => ({
  key,
  label,
  type: "number",
  min: 0.01,
  max: 99999999,
});
const date = (key, label) => ({ key, label, type: "date" });

export const forms = {
  farms: [
    text("name", "农场名称"),
    { ...text("description", "经营说明", 500), optional: true },
  ],
  plots: [
    relation("farmId", "所属农场", "farms"),
    text("name", "地块名称"),
    number("areaMu", "面积（亩）"),
    { ...text("crop", "当前作物", 80), optional: true },
  ],
  plantings: [
    relation("plotId", "所属地块", "plots"),
    text("crop", "作物", 80),
    { ...text("variety", "品种", 80), optional: true },
    number("areaMu", "种植面积（亩）"),
    date("startDate", "开始日期"),
    date("endDate", "结束日期"),
  ],
  tasks: [
    relation("plotId", "所属地块", "plots"),
    text("title", "任务名称", 120),
    choice("taskType", "农事类型", [
      "SOWING",
      "IRRIGATION",
      "FERTILIZING",
      "HARVEST",
      "INSPECTION",
      "PROTECTION",
    ]),
    date("dueDate", "计划日期"),
    { ...text("note", "备注", 500), optional: true },
  ],
  production: [
    relation("plotId", "所属地块", "plots"),
    date("recordDate", "记录日期"),
    number("yieldKg", "收获产量（kg）"),
    { ...text("note", "备注", 500), optional: true },
  ],
  devices: [
    relation("farmId", "所属农场", "farms"),
    text("name", "监测点名称"),
    choice("metric", "监测指标", ["TEMPERATURE", "HUMIDITY", "SOIL_MOISTURE"]),
    choice("adapter", "数据方式", ["MANUAL", "SIMULATED"]),
  ],
  members: [
    text("username", "登录账号", 60),
    text("displayName", "显示姓名", 80),
    {
      key: "password",
      label: "初始密码（至少 12 位）",
      type: "password",
      minLength: 12,
      max: 72,
    },
    choice("role", "成员角色", ["ADMIN", "OPERATOR", "VIEWER"]),
  ],
  "platform/tenants": [
    text("code", "租户代码（小写字母开头）", 40),
    text("name", "租户名称", 120),
    {
      key: "adminPassword",
      label: "初始管理员密码（至少 12 位）",
      type: "password",
      minLength: 12,
      max: 72,
    },
  ],
};
