// Generate a fresh MySQL 8 schema from the additive H2 schema. No database connection.
const fs = require("node:fs");
const path = require("node:path");
const source = fs
  .readFileSync(
    path.join(__dirname, "../backend/src/main/resources/schema.sql"),
    "utf8",
  )
  .replaceAll("\r\n", "\n");
const tables = new Map(
  [
    ...source.matchAll(/CREATE TABLE IF NOT EXISTS (\w+) \(([\s\S]*?)\n\);/g),
  ].map((m) => [m[1], m[2].trim()]),
);
function append(table, text) {
  if (!tables.has(table)) throw new Error(`Unknown table ${table}`);
  tables.set(table, tables.get(table) + ",\n " + text.trim());
}
for (const m of source.matchAll(
  /ALTER TABLE (\w+) ADD COLUMN IF NOT EXISTS ([^;]+);/g,
))
  append(m[1], m[2]);
for (const m of source.matchAll(
  /ALTER TABLE (\w+) ADD CONSTRAINT IF NOT EXISTS ([^;]+);/g,
))
  append(m[1], "CONSTRAINT " + m[2]);
for (const m of source.matchAll(
  /CREATE INDEX IF NOT EXISTS (\w+) ON (\w+)\(([^)]+)\);/g,
))
  append(m[2], `INDEX ${m[1]}(${m[3]})`);
const statements = [];
for (const [name, original] of tables) {
  const foreign = [];
  let body = original.replace(
    /\b(\w+) (VARCHAR\(\d+\))((?: PRIMARY KEY| NOT NULL)*) REFERENCES (\w+)\((\w+)\)( ON DELETE CASCADE)?/g,
    (_, column, type, attrs, table, key, cascade) => {
      foreign.push(
        `FOREIGN KEY(${column}) REFERENCES ${table}(${key})${cascade || ""}`,
      );
      return `${column} ${type}${attrs}`;
    },
  );
  if (foreign.length) body += ",\n " + foreign.join(",\n ");
  body = body
    .replace(/TIMESTAMP WITH TIME ZONE|\bTIMESTAMP\b/g, "DATETIME(6)")
    .replace(/\bBOOLEAN\b/g, "BIT")
    .replace(/\bCLOB\b/g, "LONGTEXT")
    .replace(
      /\b(boundary_json|bindings_json|missing_json) VARCHAR\(\d+\)/g,
      "$1 TEXT",
    );
  statements.push(
    `CREATE TABLE IF NOT EXISTS ${name} (\n ${body}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;`,
  );
}
const output =
  "-- Generated by tools/build_mysql_schema.cjs; MySQL 8 fresh databases only.\n-- DATETIME values are UTC. Existing databases require reviewed additive migrations.\n" +
  statements.join("\n\n") +
  "\n";
const target = path.join(
  __dirname,
  "../backend/src/main/resources/schema-mysql.sql",
);
if (process.argv.includes("--check")) {
  if (
    !fs.existsSync(target) ||
    fs.readFileSync(target, "utf8").replaceAll("\r\n", "\n") !== output
  )
    throw new Error("Regenerate schema-mysql.sql");
  console.log(`MySQL schema matches ${tables.size} source tables.`);
} else {
  fs.writeFileSync(target, output);
  console.log(`Generated ${tables.size} MySQL tables.`);
}
