// Generate the initial MySQL schema from the additive H2 schema. No connection details are used.
// Column additions/constraints are folded into CREATE TABLE; existing MySQL releases need explicit migrations.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const input = fs.readFileSync(path.join(root, 'backend/src/main/resources/schema.sql'), 'utf8').replace(/--[^\n]*/g, '');
const tables = new Map();
for (const raw of input.split(';').map(s=>s.trim()).filter(Boolean)) {
  let m;
  if ((m=raw.match(/^CREATE TABLE IF NOT EXISTS (\w+)\s*\(([\s\S]*)\)$/))) {
    let body = m[2], extra=[];
    body=body.replace(/(\b\w+) (VARCHAR\(\d+\)(?: PRIMARY KEY| NOT NULL)*) REFERENCES (\w+)\((\w+)\)( ON DELETE CASCADE)?/g,
      (_,col,type,table,key,cascade)=>{extra.push(`FOREIGN KEY(${col}) REFERENCES ${table}(${key})${cascade||''}`);return `${col} ${type}`;});
    tables.set(m[1],body.trim()+(extra.length?',\n '+extra.join(',\n '):''));
  } else if ((m=raw.match(/^CREATE INDEX IF NOT EXISTS (\w+) ON (\w+)\((.*)\)$/))) {
    tables.set(m[2],tables.get(m[2])+`,\n INDEX ${m[1]}(${m[3]})`);
  } else if ((m=raw.match(/^ALTER TABLE (\w+) ADD COLUMN IF NOT EXISTS ([\s\S]+)$/))) {
    tables.set(m[1],tables.get(m[1])+',\n '+m[2]);
  } else if ((m=raw.match(/^ALTER TABLE (\w+) ADD CONSTRAINT IF NOT EXISTS (\w+) ([\s\S]+)$/))) {
    tables.set(m[1],tables.get(m[1])+`,\n CONSTRAINT ${m[2]} ${m[3]}`);
  } else throw Error('Unrecognized schema statement: '+raw.slice(0,80));
}
const output='-- Generated by tools/generate_mysql_schema.cjs; MySQL 8.0.16+ / 8.4, InnoDB.\n'+[...tables].map(([name,body])=>{
  body=body.replaceAll('TIMESTAMP WITH TIME ZONE','__INSTANT__').replace(/\bTIMESTAMP\b/g,'DATETIME(6)').replaceAll('__INSTANT__','TIMESTAMP(6)').replace(/\bCLOB\b/g,'LONGTEXT');
  return `CREATE TABLE IF NOT EXISTS ${name} (\n ${body}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;`;
}).join('\n\n')+'\n';
const file=path.join(root,'backend/src/main/resources/schema-mysql.sql');
if(process.argv.includes('--check')) {
  if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==output) { console.error('MySQL schema is out of date; run node tools/generate_mysql_schema.cjs');process.exitCode=1; }
} else fs.writeFileSync(file,output);
